//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Survey_Questions = new HashSet<Survey_Questions>();
            this.SurveyResponses = new HashSet<SurveyResponse>();
        }
    
        public int ID { get; set; }
        public string Text { get; set; }
        public string QuestionType { get; set; }
        public string Options { get; set; }
    
        public virtual ICollection<Survey_Questions> Survey_Questions { get; set; }
        public virtual ICollection<SurveyResponse> SurveyResponses { get; set; }
    }
}
