//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public Survey()
        {
            this.Survey_Questions = new HashSet<Survey_Questions>();
            this.SurveyResponses = new HashSet<SurveyResponse>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public int CreatedBy { get; set; }
        public bool Publish { get; set; }
    
        public virtual ICollection<Survey_Questions> Survey_Questions { get; set; }
        public virtual ICollection<SurveyResponse> SurveyResponses { get; set; }
        public virtual User User { get; set; }
    }
}
